version: '3.2'



services:

# Container for Load Balancer
  load_balancer:
    env_file:
      - .env
    image: teamcloudboost/glue-with-loadbalancer:loadbalancer
    container_name: glue-loadbalancer
    restart: unless-stopped
    working_dir: /public_html
    ports:
      - 80:80

# Container for Web Server -1
  server-1:
    env_file:
      - .env
    image: teamcloudboost/glue-with-loadbalancer:server-1
    container_name: glue-webserver-1
    restart: unless-stopped
    working_dir: /public_html
    ports:
      - ${SERVER_1_PORT}:${SERVER_1_PORT}

# Container for Web Server -2
  server-2:
    env_file:
      - .env
    image: teamcloudboost/glue-with-loadbalancer:server-2
    container_name: glue-webserver-2
    restart: unless-stopped
    working_dir: /public_html
    ports:
      - ${SERVER_2_PORT}:${SERVER_2_PORT}

# Container for PHP 1
  php-1:
    env_file:
      - .env
    image: teamcloudboost/glue-with-loadbalancer:php-1
    container_name: glue-backend-1
    restart: unless-stopped
    ports:
      - ${PHP_FPM_1_PORT}:${PHP_FPM_1_PORT}

# Container for PHP 2
  php-2:
    env_file:
      - .env
    image: teamcloudboost/glue-with-loadbalancer:php-2
    container_name: glue-backend-2
    restart: unless-stopped
    ports:
      - ${PHP_FPM_2_PORT}:${PHP_FPM_2_PORT}
# Container for Database
  db:
    env_file:
      - .env
    image: teamcloudboost/glue-with-loadbalancer:database
    container_name: glue-database
    restart: unless-stopped
    ports:
      - ${APP_DB_PORT}:${APP_DB_PORT}