FROM alpine


COPY ./config/nginx/load_balancer.conf /etc/nginx/conf.d/default.conf
COPY ./Entrypoint/loadbalancer-docker-entrypoint.sh /loadbalancer-docker-entrypoint.sh

## For reserving Purpose
RUN apt add nginx; \
    cp /etc/nginx/conf.d/default.conf /default.conf.bak;

RUN ["chmod", "+x", "/loadbalancer-docker-entrypoint.sh"]

ENTRYPOINT [ "/loadbalancer-docker-entrypoint.sh" ]

