FROM ubuntu


COPY ./config/nginx/load_balancer.conf /etc/nginx/sites-available/default
COPY ./Entrypoint/loadbalancer-docker-entrypoint.sh /loadbalancer-docker-entrypoint.sh

## For reserving Purpose
RUN apt update; apt install nginx -y; \
    cp /etc/nginx/sites-available/default /default.conf.bak;

RUN ["chmod", "+x", "/loadbalancer-docker-entrypoint.sh"]

ENTRYPOINT [ "source", "/loadbalancer-docker-entrypoint.sh" ]

